Pixel Potter: /Users/KJ/714227-Butkow-835842-daSilva-2017-Project/test-source-code/PixelPotterTests.cpp File Reference
PixelPotterTests.cpp File Reference
#include "Player.h"
#include "Enemy.h"
#include "PlayerBullet.h"
#include "EnemyBullet.h"
#include "Asteroid.h"
#include "Satellite.h"
#include "userInput.h"
#include "movingEntity.h"
#include "MovingShootingEntity.h"
#include "CollisionManager.h"
#include "LaserGenerator.h"
#include "LaserArc.h"
#include "gameState.h"
#include <cmath>
#include <iostream>
#include "doctest.h"
Macros
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Functions
TEST_SUITE ("Player_movement_and_spawning")
TEST_SUITE ("Player_bullet_movement_and_spawning")
TEST_SUITE ("Enemy_movement_and_spawning")
TEST_SUITE ("Enemy_bullet_movement_and_spawning")
TEST_SUITE ("Asteroid_movement_and_spawning")
TEST_SUITE ("Satellite_movement_and_spawning")
TEST_SUITE ("Satellite_bullet_movement_and_spawning")
TEST_SUITE ("Laser_generator_and_arc_movement_and_spawning")
TEST_SUITE ("Lives")
TEST_SUITE ("Collision_detection")
TEST_SUITE ("Entity_deletion")
TEST_SUITE ("Player_bullet_upgrade")
TEST_SUITE ("Game_state")
Macro Definition Documentation
DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Definition at line 17 of file PixelPotterTests.cpp.
Function Documentation
TEST_SUITE() [1/13]
TEST_SUITE ("Player_movement_and_spawning")
Definition at line 26 of file PixelPotterTests.cpp.
References Player::getAngle(), Player::getPosition(), Player::MovementDirection(), NoButtonPress, PressLeft, PressRight, and Player::Update().
TEST_SUITE() [2/13]
TEST_SUITE ("Player_bullet_movement_and_spawning")
Definition at line 105 of file PixelPotterTests.cpp.
References movingEntity::entityList, Player::getAngle(), Player::getPosition(), Player::MovementDirection(), NoButtonPress, PlayerBulletEntity, PressLeft, PressRight, PressSpace, and Player::Update().
TEST_SUITE() [3/13]
TEST_SUITE ("Enemy_movement_and_spawning")
Definition at line 439 of file PixelPotterTests.cpp.
References Enemy::getAngle(), Enemy::getPosition(), Enemy::getRadius(), and Enemy::Update().
TEST_SUITE() [4/13]
TEST_SUITE ("Enemy_bullet_movement_and_spawning")
Definition at line 523 of file PixelPotterTests.cpp.
References Enemy::createBullets(), EnemyBulletEntity, movingEntity::entityList, Enemy::getAngle(), Enemy::getPosition(), Enemy::getRadius(), and Enemy::Update().
TEST_SUITE() [5/13]
TEST_SUITE ("Asteroid_movement_and_spawning")
Definition at line 714 of file PixelPotterTests.cpp.
References AsteroidEntity, movingEntity::entityList, Player::getAngle(), Player::MovementDirection(), PressRight, and Player::Update().
TEST_SUITE() [6/13]
TEST_SUITE ("Satellite_movement_and_spawning")
Definition at line 872 of file PixelPotterTests.cpp.
References movingEntity::entityList, Player::getAngle(), Player::getPosition(), and SatelliteEntity.
TEST_SUITE() [7/13]
TEST_SUITE ("Satellite_bullet_movement_and_spawning")
Definition at line 1069 of file PixelPotterTests.cpp.
References Satellite::createBullets(), EnemyBulletEntity, movingEntity::entityList, Player::getAngle(), Player::getPosition(), Satellite::getPosition(), Player::MovementDirection(), PressLeft, PressRight, and Player::Update().
TEST_SUITE() [8/13]
TEST_SUITE ("Laser_generator_and_arc_movement_and_spawning")
Definition at line 1356 of file PixelPotterTests.cpp.
References ArcEntity, movingEntity::entityList, LaserArc::getAngle(), and LaserEntity.
TEST_SUITE() [9/13]
TEST_SUITE ("Lives")
Definition at line 1535 of file PixelPotterTests.cpp.
References Enemy::createBullets(), Satellite::createBullets(), movingEntity::entityList, LaserArc::getAngle(), Player::getAngle(), Player::getPosition(), Player::MovementDirection(), PressSpace, and Player::Update().
TEST_SUITE() [10/13]
TEST_SUITE ("Collision_detection")
Definition at line 1847 of file PixelPotterTests.cpp.
References CollisionManager::checkCollision(), Satellite::createBullets(), movingEntity::entityList, LaserArc::getAngle(), Player::getAngle(), Player::getPosition(), Player::MovementDirection(), PressLeft, PressSpace, and Player::Update().
TEST_SUITE() [11/13]
TEST_SUITE ("Entity_deletion")
Definition at line 2187 of file PixelPotterTests.cpp.
References Enemy::createBullets(), Satellite::createBullets(), CollisionManager::entityCleanUp(), movingEntity::entityList, and LaserArc::getAngle().
TEST_SUITE() [12/13]
TEST_SUITE ("Player_bullet_upgrade")
Definition at line 2373 of file PixelPotterTests.cpp.
References movingEntity::entityList, Player::getAngle(), Player::getPosition(), Satellite::ResetSatellites(), Player::Update(), and Satellite::~Satellite().
TEST_SUITE() [13/13]
TEST_SUITE ("Game_state")
Definition at line 2431 of file PixelPotterTests.cpp.
References CollisionManager::entityCleanUp(), movingEntity::entityList, lose, and playing.