Pixel Potter: entityCreator Class Reference
entityCreator Class Reference
entityCreator class - handles the creation of all of the enemy entities (Enemy, LaserGenerator, LaserArc, Asteroid, Satellite)
#include <entityCreator.h>
Public Member Functions
entityCreator (const std::shared_ptr< Clock > &gameClock, int maxEnemies, const std::shared_ptr< Player > &playerPtr)
Constructor. Creates an entityCreator object.
~entityCreator ()
Destructor.
void create ()
Function to create all of the various enemy entities.
void reset ()
Function to reset the required variables upon restarting the game.
Private Member Functions
void CreateEnemy ()
Function to create Enemy entities.
void CreateAsteroid ()
Function to create Asteroid entities.
void CreateSatellite ()
Function to create Satellite entities.
void CreateLaser ()
Function to create LaserGenerator and LaserArc entities.
Private Attributes
std::shared_ptr< Clock > _entityClock
std::shared_ptr< Player > _playerPtr
float _timeEnemy
float _timeAsteroid
float _timeSatellite
float _generateAsteroid
float _generateEnemy
int _MAXENEMIES
Detailed Description
entityCreator class - handles the creation of all of the enemy entities (Enemy, LaserGenerator, LaserArc, Asteroid, Satellite)
Definition at line 18 of file entityCreator.h.
Constructor & Destructor Documentation
entityCreator()
entityCreator::entityCreator (const std::shared_ptr< Clock > & gameClock, int maxEnemies, const std::shared_ptr< Player > & playerPtr)
Constructor. Creates an entityCreator object.
Parameters
gameClock is a shared pointer to a Clock object
maxEnemies is an int containing the maximum number of enemies to be created
playerPtr is a shared pointer to the Player object
Definition at line 3 of file entityCreator.cpp.
References _generateAsteroid, _generateEnemy, _MAXENEMIES, _playerPtr, _timeAsteroid, _timeEnemy, and _timeSatellite.
~entityCreator()
entityCreator::~entityCreator ()
Destructor.
Definition at line 15 of file entityCreator.cpp.
Member Function Documentation
create()
void entityCreator::create ()
Function to create all of the various enemy entities.
Definition at line 19 of file entityCreator.cpp.
References CreateAsteroid(), CreateEnemy(), CreateLaser(), and CreateSatellite().
Referenced by Game::Update().
CreateAsteroid()
void entityCreator::CreateAsteroid () private
Function to create Asteroid entities.
Definition at line 45 of file entityCreator.cpp.
References _entityClock, _generateAsteroid, _playerPtr, _timeAsteroid, and movingEntity::entityList.
Referenced by create().
CreateEnemy()
void entityCreator::CreateEnemy () private
Function to create Enemy entities.
Definition at line 27 of file entityCreator.cpp.
References _entityClock, _generateEnemy, _MAXENEMIES, _timeEnemy, movingEntity::entityList, Enemy::getNumberofEnemiesAlive(), and Enemy::getTotalNumberofEnemies().
Referenced by create().
CreateLaser()
void entityCreator::CreateLaser () private
Function to create LaserGenerator and LaserArc entities.
Definition at line 73 of file entityCreator.cpp.
References _entityClock, _timeSatellite, movingEntity::entityList, LaserArc::getAngle(), and LaserGenerator::getNumberofLasersAlive().
Referenced by create().
CreateSatellite()
void entityCreator::CreateSatellite () private
Function to create Satellite entities.
Definition at line 57 of file entityCreator.cpp.
References _entityClock, _playerPtr, _timeSatellite, movingEntity::entityList, and Satellite::getNumberofSatellitesAlive().
Referenced by create().
reset()
void entityCreator::reset ()
Function to reset the required variables upon restarting the game.
Definition at line 87 of file entityCreator.cpp.
References _entityClock, _generateAsteroid, _generateEnemy, and _timeEnemy.
Referenced by Game::Game(), and Game::Reset().
Member Data Documentation
_entityClock
std::shared_ptr<Clock> entityCreator::_entityClock private
Definition at line 59 of file entityCreator.h.
Referenced by CreateAsteroid(), CreateEnemy(), CreateLaser(), CreateSatellite(), and reset().
_generateAsteroid
float entityCreator::_generateAsteroid private
Definition at line 64 of file entityCreator.h.
Referenced by CreateAsteroid(), entityCreator(), and reset().
_generateEnemy
float entityCreator::_generateEnemy private
Definition at line 65 of file entityCreator.h.
Referenced by CreateEnemy(), entityCreator(), and reset().
_MAXENEMIES
int entityCreator::_MAXENEMIES private
Definition at line 66 of file entityCreator.h.
Referenced by CreateEnemy(), and entityCreator().
_playerPtr
std::shared_ptr<Player> entityCreator::_playerPtr private
Definition at line 60 of file entityCreator.h.
Referenced by CreateAsteroid(), CreateSatellite(), and entityCreator().
_timeAsteroid
float entityCreator::_timeAsteroid private
Definition at line 62 of file entityCreator.h.
Referenced by CreateAsteroid(), and entityCreator().
_timeEnemy
float entityCreator::_timeEnemy private
Definition at line 61 of file entityCreator.h.
Referenced by CreateEnemy(), entityCreator(), and reset().
_timeSatellite
float entityCreator::_timeSatellite private
Definition at line 63 of file entityCreator.h.
Referenced by CreateLaser(), CreateSatellite(), and entityCreator().
The documentation for this class was generated from the following files:
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/entityCreator.h
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/entityCreator.cpp