Pixel Potter: Game Class Reference
Game Class Reference
Game class - handles all of the logic required in the operating of the game.
#include <Game.h>
Public Member Functions
Game ()
Default Constructor. Creates a Game object.
~Game ()
Destructor.
Private Member Functions
void GameLoop ()
Function ot control the game loop. The function calls the Update, Render, RestartClock functions.
void Update ()
Function that updates all of the entities involved in the game. This includes calling the functions that create the various enemy entities, updating the positions of the entities, calling the function that checks for collisions, calling the function that deletes expired entities.
void Render ()
Function that renders the movingEntity objects to the screen. The function loops through the vector of movingEntity and calls the Window show() function on each entity.
void RestartClock ()
Function that calls the Clock RestartClock function.
void Reset ()
Function that resets all the necessary variables upon restarting a new game.
float GetTime ()
Function that calls the Clock GetTime function.
Private Attributes
float _elapsedTime
bool _bulletExists
const int _MAXENEMIES =20
std::shared_ptr< Clock > _gameClock {new Clock{}}
std::shared_ptr< Player > _playerPtr { new Player{}}
Window _window
CollisionManager _collision
entityCreator _create
Detailed Description
Game class - handles all of the logic required in the operating of the game.
Definition at line 20 of file Game.h.
Constructor & Destructor Documentation
Game()
Game::Game ()
Default Constructor. Creates a Game object.
Definition at line 3 of file Game.cpp.
References _bulletExists, _create, _elapsedTime, _MAXENEMIES, _playerPtr, _window, movingEntity::entityList, GameLoop(), playing, entityCreator::reset(), Window::setGameState(), Window::setMaximumEnemies(), and Window::SplashScreen().
~Game()
Game::~Game ()
Destructor.
Definition at line 18 of file Game.cpp.
Member Function Documentation
GameLoop()
void Game::GameLoop () private
Function ot control the game loop. The function calls the Update, Render, RestartClock functions.
Definition at line 22 of file Game.cpp.
References _window, Window::IsDone(), Render(), RestartClock(), and Update().
Referenced by Game().
GetTime()
float Game::GetTime () private
Function that calls the Clock GetTime function.
Definition at line 77 of file Game.cpp.
References _gameClock.
Referenced by Update().
Render()
void Game::Render () private
Function that renders the movingEntity objects to the screen. The function loops through the vector of movingEntity and calls the Window show() function on each entity.
Definition at line 70 of file Game.cpp.
References _window, and Window::Draw().
Referenced by GameLoop().
Reset()
void Game::Reset () private
Function that resets all the necessary variables upon restarting a new game.
Definition at line 87 of file Game.cpp.
References _create, _playerPtr, _window, movingEntity::entityList, playing, entityCreator::reset(), Enemy::ResetEnemies(), Satellite::ResetSatellites(), and Window::setGameState().
Referenced by Update().
RestartClock()
void Game::RestartClock () private
Function that calls the Clock RestartClock function.
Definition at line 82 of file Game.cpp.
References _gameClock.
Referenced by GameLoop().
Update()
void Game::Update () private
Function that updates all of the entities involved in the game. This includes calling the functions that create the various enemy entities, updating the positions of the entities, calling the function that checks for collisions, calling the function that deletes expired entities.
Definition at line 33 of file Game.cpp.
References _collision, _create, _MAXENEMIES, _playerPtr, _window, CollisionManager::checkCollision(), entityCreator::create(), CollisionManager::entityCleanUp(), movingEntity::entityList, Window::getGameState(), Enemy::getNumberofEnemiesAlive(), GetTime(), Enemy::getTotalNumberofEnemies(), Reset(), Window::reset, Window::setGameState(), Window::setLivesRemaining(), Window::Update(), and win.
Referenced by GameLoop().
Member Data Documentation
_bulletExists
bool Game::_bulletExists private
Definition at line 65 of file Game.h.
Referenced by Game().
_collision
CollisionManager Game::_collision private
Definition at line 71 of file Game.h.
Referenced by Update().
_create
entityCreator Game::_create private
Definition at line 72 of file Game.h.
Referenced by Game(), Reset(), and Update().
_elapsedTime
float Game::_elapsedTime private
Definition at line 64 of file Game.h.
Referenced by Game().
_gameClock
std::shared_ptr< Clock> Game::_gameClock {new Clock{}} private
Definition at line 68 of file Game.h.
Referenced by GetTime(), and RestartClock().
_MAXENEMIES
const int Game::_MAXENEMIES =20 private
Definition at line 66 of file Game.h.
Referenced by Game(), and Update().
_playerPtr
std::shared_ptr<Player> Game::_playerPtr { new Player{}} private
Definition at line 69 of file Game.h.
Referenced by Game(), Reset(), and Update().
_window
Window Game::_window private
Definition at line 70 of file Game.h.
Referenced by Game(), GameLoop(), Render(), Reset(), and Update().
The documentation for this class was generated from the following files:
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/Game.h
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/Game.cpp