Pixel Potter: Window Class Reference
Window Class Reference
Window class. Acts as an Interface - creates a window, draws the entities, displays the splashscreens.
#include <Window.h>
Public Member Functions
Window ()
Default Constructor. Creates a new Window.
void Draw ()
Function to draw the entities to the screen and set the background. The function clears the SFML window prior to drawing and sets the background for the main game. The function also calls the show() function to display the entities on the screen.
userInput Update ()
Function that converts the keyboard input to a userInput type The function is used to seperate the logic and interface layers.
bool IsDone ()
Function that checks the status of the SFML window (open or closed)
void SplashScreen ()
Function that displays the splashscreen at the start of the game.
void show (const std::shared_ptr< movingEntity > &entity)
Function that draws the entity to the screen.
void setGameState (gameState state)
Function that gets the current state of the game and calls the win/lose screen.
void getGameState ()
Function that gets the current state of the game.
void setLivesRemaining (int lives)
Function that sets the number of Player lives remaining.
void setMaximumEnemies (int maxEnemies)
Function that sets the maximum number of Enemy entities.
Public Attributes
bool reset
Private Member Functions
void closeWindow ()
Function to close the SFML window.
void BeginDraw ()
Function to clear the SFML window prior to drawing.
void EndDraw ()
Function to display the SFML window.
void fileLoader ()
Function that loads the required images.
void drawText ()
Function that draws the reqired text to the screen.
bool End ()
Function that ends the splashscreen by either starting the game or closing the window.
void DisplayGameState (sf::Sprite &texture)
Function that displays the win or lose screen.
void textSetup (float xPos, float yPos, sf::Text &text)
Function that sets up the text to be drawn on the screen.
Private Attributes
userInput _keyBoard
sf::RenderWindow _window
sf::Texture _splashTexture
sf::Texture _loseTexture
sf::Texture _winTexture
sf::Texture _backgroundTexture
sf::Font _font
bool _isDone
bool _disableShooting
gameState _state
int _playerLives
int _enemies
Detailed Description
Window class. Acts as an Interface - creates a window, draws the entities, displays the splashscreens.
Definition at line 25 of file Window.h.
Constructor & Destructor Documentation
Window()
Window::Window ()
Default Constructor. Creates a new Window.
Definition at line 3 of file Window.cpp.
References _disableShooting, _isDone, _window, and fileLoader().
Member Function Documentation
BeginDraw()
void Window::BeginDraw () private
Function to clear the SFML window prior to drawing.
Definition at line 66 of file Window.cpp.
References _window.
Referenced by DisplayGameState(), and SplashScreen().
closeWindow()
void Window::closeWindow () private
Function to close the SFML window.
Definition at line 27 of file Window.cpp.
References _window.
Referenced by End().
DisplayGameState()
void Window::DisplayGameState (sf::Sprite & texture) private
Function that displays the win or lose screen.
Definition at line 150 of file Window.cpp.
References _window, BeginDraw(), End(), and movingEntity::entityList.
Referenced by getGameState().
Draw()
void Window::Draw ()
Function to draw the entities to the screen and set the background. The function clears the SFML window prior to drawing and sets the background for the main game. The function also calls the show() function to display the entities on the screen.
Definition at line 32 of file Window.cpp.
References _backgroundTexture, _window, drawText(), EndDraw(), movingEntity::entityList, and show().
Referenced by Game::Render().
drawText()
void Window::drawText () private
Function that draws the reqired text to the screen.
Definition at line 46 of file Window.cpp.
References _enemies, _font, _playerLives, _window, Enemy::getNumberofEnemiesKilled(), and textSetup().
Referenced by Draw().
End()
bool Window::End () private
Function that ends the splashscreen by either starting the game or closing the window.
Returns
bool that indicates whether the window should be closed or not
Definition at line 132 of file Window.cpp.
References _isDone, _window, and closeWindow().
Referenced by DisplayGameState(), and SplashScreen().
EndDraw()
void Window::EndDraw () private
Function to display the SFML window.
Definition at line 71 of file Window.cpp.
References _window.
Referenced by Draw().
fileLoader()
void Window::fileLoader () private
Function that loads the required images.
Definition at line 12 of file Window.cpp.
References _backgroundTexture, _font, _loseTexture, _splashTexture, and _winTexture.
Referenced by Window().
getGameState()
void Window::getGameState ()
Function that gets the current state of the game.
Definition at line 196 of file Window.cpp.
References _loseTexture, _state, _winTexture, DisplayGameState(), lose, playing, reset, and win.
Referenced by Game::Update().
IsDone()
bool Window::IsDone ()
Function that checks the status of the SFML window (open or closed)
Returns
bool indicating whether the SFML window should be closed or not
Definition at line 76 of file Window.cpp.
References _isDone.
Referenced by Game::GameLoop().
setGameState()
void Window::setGameState (gameState state)
Function that gets the current state of the game and calls the win/lose screen.
Parameters
state is a gameState variable that indicates the state of the game
Definition at line 217 of file Window.cpp.
References _state.
Referenced by Game::Game(), Game::Reset(), and Game::Update().
setLivesRemaining()
void Window::setLivesRemaining (int lives)
Function that sets the number of Player lives remaining.
Definition at line 222 of file Window.cpp.
References _playerLives.
Referenced by Game::Update().
setMaximumEnemies()
void Window::setMaximumEnemies (int maxEnemies)
Function that sets the maximum number of Enemy entities.
Definition at line 227 of file Window.cpp.
References _enemies.
Referenced by Game::Game().
show()
void Window::show (const std::shared_ptr< movingEntity > & entity)
Function that draws the entity to the screen.
Parameters
entity is a shared pointer to a movingEntity object
Definition at line 167 of file Window.cpp.
References _window.
Referenced by Draw().
SplashScreen()
void Window::SplashScreen ()
Function that displays the splashscreen at the start of the game.
Definition at line 116 of file Window.cpp.
References _splashTexture, _window, BeginDraw(), and End().
Referenced by Game::Game().
textSetup()
void Window::textSetup (float xPos, float yPos, sf::Text & text) private
Function that sets up the text to be drawn on the screen.
Parameters
xPos is a float indicating the x position of the text
yPos is a float indicating the y position of the text
text is a reference to an sf::Text containing the text to be altered
Definition at line 58 of file Window.cpp.
Referenced by drawText().
Update()
userInput Window::Update ()
Function that converts the keyboard input to a userInput type The function is used to seperate the logic and interface layers.
Returns
userInput
Definition at line 81 of file Window.cpp.
References _disableShooting, _isDone, _keyBoard, _window, NoButtonPress, PressLeft, PressRight, PressSpace, and reset.
Referenced by Game::Update().
Member Data Documentation
_backgroundTexture
sf::Texture Window::_backgroundTexture private
Definition at line 124 of file Window.h.
Referenced by Draw(), and fileLoader().
_disableShooting
bool Window::_disableShooting private
Definition at line 127 of file Window.h.
Referenced by Update(), and Window().
_enemies
int Window::_enemies private
Definition at line 130 of file Window.h.
Referenced by drawText(), and setMaximumEnemies().
_font
sf::Font Window::_font private
Definition at line 125 of file Window.h.
Referenced by drawText(), and fileLoader().
_isDone
bool Window::_isDone private
Definition at line 126 of file Window.h.
Referenced by End(), IsDone(), Update(), and Window().
_keyBoard
userInput Window::_keyBoard private
Definition at line 119 of file Window.h.
Referenced by Update().
_loseTexture
sf::Texture Window::_loseTexture private
Definition at line 122 of file Window.h.
Referenced by fileLoader(), and getGameState().
_playerLives
int Window::_playerLives private
Definition at line 129 of file Window.h.
Referenced by drawText(), and setLivesRemaining().
_splashTexture
sf::Texture Window::_splashTexture private
Definition at line 121 of file Window.h.
Referenced by fileLoader(), and SplashScreen().
_state
gameState Window::_state private
Definition at line 128 of file Window.h.
Referenced by getGameState(), and setGameState().
_window
sf::RenderWindow Window::_window private
Definition at line 120 of file Window.h.
Referenced by BeginDraw(), closeWindow(), DisplayGameState(), Draw(), drawText(), End(), EndDraw(), show(), SplashScreen(), Update(), and Window().
_winTexture
sf::Texture Window::_winTexture private
Definition at line 123 of file Window.h.
Referenced by fileLoader(), and getGameState().
reset
bool Window::reset
Definition at line 79 of file Window.h.
Referenced by getGameState(), Game::Update(), and Update().
The documentation for this class was generated from the following files:
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/Window.h
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/Window.cpp