Pixel Potter: CollisionManager Class Reference
CollisionManager Class Reference
CollisionManager class - used to check collisions between entities and manage the deletions of entities.
#include <CollisionManager.h>
Public Member Functions
CollisionManager ()
Default constructor. Creates a CollisionManager object.
void checkCollision ()
Function to check all the collisions of the required entities.
bool Collision (int i, int j)
Function to check if two entities have collided.
gameState entityCleanUp (const std::shared_ptr< Player > &playerPtr)
Function to delete entities that have collided, or are no longer valid.
Private Attributes
bool _collidedArc
Detailed Description
CollisionManager class - used to check collisions between entities and manage the deletions of entities.
Definition at line 14 of file CollisionManager.h.
Constructor & Destructor Documentation
CollisionManager()
CollisionManager::CollisionManager ()
Default constructor. Creates a CollisionManager object.
Definition at line 3 of file CollisionManager.cpp.
Member Function Documentation
checkCollision()
void CollisionManager::checkCollision ()
Function to check all the collisions of the required entities.
Definition at line 8 of file CollisionManager.cpp.
References _collidedArc, ArcEntity, AsteroidEntity, Collision(), EnemyBulletEntity, EnemyEntity, movingEntity::entityList, LaserEntity, PlayerBulletEntity, PlayerEntity, and SatelliteEntity.
Referenced by TEST_SUITE(), and Game::Update().
Collision()
bool CollisionManager::Collision (int i, int j)
Function to check if two entities have collided.
Parameters
i is an integer containing the index of an entity
j is an integer containing the index of the other entity
Returns
bool true if a collision has occured and false otherwise
Definition at line 114 of file CollisionManager.cpp.
References movingEntity::entityList.
Referenced by checkCollision().
entityCleanUp()
gameState CollisionManager::entityCleanUp (const std::shared_ptr< Player > & playerPtr)
Function to delete entities that have collided, or are no longer valid.
Parameters
playerPtr is a shared pointer to the Player object
Returns
gameState indicating whether the game has been lost or is still ongoing
Definition at line 133 of file CollisionManager.cpp.
References movingEntity::entityList, lose, and playing.
Referenced by TEST_SUITE(), and Game::Update().
Member Data Documentation
_collidedArc
bool CollisionManager::_collidedArc private
Definition at line 40 of file CollisionManager.h.
Referenced by checkCollision().
The documentation for this class was generated from the following files:
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/CollisionManager.h
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/CollisionManager.cpp