Pixel Potter: Player Class Reference
Player Class Reference
Player class - represents the harry potter player Inherits from the MovingShootingEntity class.
#include <Player.h>
Public Member Functions
Player ()
Default Constructor. Calls the MovingShootingEntity constructor explicitly. Creates a Player entity on the perimeter of the circle at 270 degrees.
virtual floatVector getPosition () override
Inherited from MovingShootingEntity.
virtual float getAngle () override
Inherited from MovingShootingEntity.
virtual float getRadius () override
Inherited from MovingShootingEntity.
int MovementDirection (userInput event)
Function returning an integer based on the required movement of the player.
virtual void Update (int direction, float timeElapsed) override
Inherited from MovingShootingEntity. Updates the current position of the Player.
virtual EntityList getEntityType () override
Inherited from MovingShootingEntity.
void reset ()
Function to reset all the variables required for the player class.
virtual void createBullets () override
Inherited from MovingShootingEntity. Generates PlayerBullet entities.
virtual std::vector< int > getColour () override
Function to get the required colour of the entity. Overwritten from movingEntity since the Player changes colour when he loses lives.
Public Member Functions inherited from MovingShootingEntity
MovingShootingEntity (float entityWidth, float entityHeight, int lives, int red, int blue, int green, const string &texture)
Constructor. Calls the movingEntity constructor explicitly.
Public Member Functions inherited from movingEntity
movingEntity (float entityWidth, float entityHeight, int lives, int red, int blue, int green, const string &texture)
Constructor.
floatVector getBodySize ()
Function to get the size of the entity.
int getLives ()
Function to get the number of lives remaining.
void collide ()
Function to indicate that a collision has occurred. The function decreases the number of lives of the entity.
string getTextureName ()
Function to get the name of the texture to be loaded.
Private Member Functions
virtual void calculatePosition (const bool &direction, float factor) override
Inherited from MovingShootingEntity. Increments or decrements the Player angle and calculates the position of the Player.
Private Attributes
const int _numberLives = 5
float _speed = 0.9f
double _theta
const double _x_center = 1920.0f / 2.0f
const double _y_center = 1080.0f / 2.0f
const double _radius = 480.0f
EntityList _entityType
std::vector< int > _upgradeBullets
Additional Inherited Members
Static Public Attributes inherited from movingEntity
static std::vector< std::shared_ptr< movingEntity > > entityList
Static vector of all movingEntities.
Protected Member Functions inherited from movingEntity
void setLives (int life)
Function to set the number of lives remaining.
Protected Attributes inherited from movingEntity
float _scaleX
float _scaleY
int _red
int _blue
int _green
Detailed Description
Player class - represents the harry potter player Inherits from the MovingShootingEntity class.
Definition at line 18 of file Player.h.
Constructor & Destructor Documentation
Player()
Player::Player ()
Default Constructor. Calls the MovingShootingEntity constructor explicitly. Creates a Player entity on the perimeter of the circle at 270 degrees.
Definition at line 3 of file Player.cpp.
References _entityType, getPosition(), and PlayerEntity.
Member Function Documentation
calculatePosition()
void Player::calculatePosition (const bool & direction, float factor) override private virtual
Inherited from MovingShootingEntity. Increments or decrements the Player angle and calculates the position of the Player.
Parameters
direction is a bool indicating whether the angle must be incremented or decremented
factor is a float containing the amount by which the angle should be incremented or decremented. factor is dependent on the elapsed time
Implements MovingShootingEntity.
Definition at line 62 of file Player.cpp.
References _theta, and getPosition().
Referenced by Update().
createBullets()
void Player::createBullets () override virtual
Inherited from MovingShootingEntity. Generates PlayerBullet entities.
Implements MovingShootingEntity.
Definition at line 93 of file Player.cpp.
References _theta, _upgradeBullets, movingEntity::entityList, Satellite::getNumberofSatellitesKilled(), and Satellite::getTotalNumberofSatellites().
Referenced by Update().
getAngle()
float Player::getAngle () override virtual
Inherited from MovingShootingEntity.
Returns
current Player angle
Implements MovingShootingEntity.
Definition at line 82 of file Player.cpp.
References _theta.
Referenced by TEST_SUITE().
getColour()
std::vector< int > Player::getColour () override virtual
Function to get the required colour of the entity. Overwritten from movingEntity since the Player changes colour when he loses lives.
Returns
vector of integers containing the RGB values of the Player colour
Reimplemented from movingEntity.
Definition at line 130 of file Player.cpp.
References movingEntity::_blue, movingEntity::_green, movingEntity::_red, and movingEntity::getLives().
getEntityType()
EntityList Player::getEntityType () override virtual
Inherited from MovingShootingEntity.
Returns
an EntityList type containing the type of entity
Implements MovingShootingEntity.
Definition at line 125 of file Player.cpp.
References _entityType.
getPosition()
floatVector Player::getPosition () override virtual
Inherited from MovingShootingEntity.
Returns
vector of floats containing the current Player position
Implements MovingShootingEntity.
Definition at line 74 of file Player.cpp.
References _radius, _theta, _x_center, and _y_center.
Referenced by calculatePosition(), Player(), reset(), TEST_SUITE(), and Update().
getRadius()
float Player::getRadius () override virtual
Inherited from MovingShootingEntity.
Returns
float containing the current Player radius
Implements MovingShootingEntity.
Definition at line 88 of file Player.cpp.
References _radius.
MovementDirection()
int Player::MovementDirection (userInput event)
Function returning an integer based on the required movement of the player.
Parameters
event takes in a userInput type indicating the user's interaction with the keyboard
Returns
int relating to the type of movement required based on the userInput
Definition at line 20 of file Player.cpp.
References NoButtonPress, PressLeft, PressRight, and PressSpace.
Referenced by TEST_SUITE().
reset()
void Player::reset ()
Function to reset all the variables required for the player class.
Definition at line 12 of file Player.cpp.
References _numberLives, _theta, _upgradeBullets, getPosition(), and movingEntity::setLives().
Update()
void Player::Update (int direction, float timeElapsed) override virtual
Inherited from MovingShootingEntity. Updates the current position of the Player.
Parameters
direction indicates the direction that the Player needs to travel in based on the user input
timeElapsed is a float containing the time since the last movement occurred
Implements MovingShootingEntity.
Definition at line 37 of file Player.cpp.
References _speed, calculatePosition(), createBullets(), and getPosition().
Referenced by TEST_SUITE().
Member Data Documentation
_entityType
EntityList Player::_entityType private
Definition at line 93 of file Player.h.
Referenced by getEntityType(), and Player().
_numberLives
const int Player::_numberLives = 5 private
Definition at line 87 of file Player.h.
Referenced by reset().
_radius
const double Player::_radius = 480.0f private
Definition at line 92 of file Player.h.
Referenced by getPosition(), and getRadius().
_speed
float Player::_speed = 0.9f private
Definition at line 88 of file Player.h.
Referenced by Update().
_theta
double Player::_theta private
Definition at line 89 of file Player.h.
Referenced by calculatePosition(), createBullets(), getAngle(), getPosition(), and reset().
_upgradeBullets
std::vector<int> Player::_upgradeBullets private
Definition at line 94 of file Player.h.
Referenced by createBullets(), and reset().
_x_center
const double Player::_x_center = 1920.0f / 2.0f private
Definition at line 90 of file Player.h.
Referenced by getPosition().
_y_center
const double Player::_y_center = 1080.0f / 2.0f private
Definition at line 91 of file Player.h.
Referenced by getPosition().
The documentation for this class was generated from the following files:
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/Player.h
/Users/KJ/714227-Butkow-835842-daSilva-2017-Project/game-source-code/Player.cpp